version: "3.8"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception
    build:
      context: mariadb
      dockerfile: Dockerfile
      args:
        - SQL_DATABASE=${SQL_DATABASE}
        - SQL_USER=${SQL_USER}
        - SQL_PASSWORD=${SQL_PASSWORD}
        - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 5s
    env_file: .env
    restart: on-failure
    expose:
      - "3306"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ${HOME}/wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - ${HOME}/wordpress:/var/www/html
    networks:
      - inception
    build:
      context: wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    expose:
      - "9000"
volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${HOME}/data/mariadb

networks:
  inception:
    driver: bridge
